### ISSUE TITLE
Codeforces doesn't work with extension

### ISSUE THREAD

**Issue by adamant-pwn** [relay-chat/RIPs#17]
https://codeforces.com

It's clearly blank when I try to reach it with extension on.

**Comment by sewinter** [comment]
Hi @adamant-pwn, thanks for reporting. The issue is that Codeforces has this script tag on the initial mount: 
```
<script type="text/javascript">
    if (window.parent.frames.length > 0) {
        window.stop();
    }
</script>
```

Because Relay adds an iframe to the page, it calls the stop function on the window, preventing further resource loading. The fix is pretty simple. We'll make sure it goes into the next release.
