### ISSUE TITLE
Firefox blocks in-app links as if they were pop-ups from the domain of the current tab

### ISSUE THREAD

**Issue by birchmd** [relay-chat/RIPs#2]
This includes redirects from the app from clicking on notifications.

This is pretty annoying as I do not want to give websites permission to show pop-ups just to be able to smoothly follow in-app links/notifications.

Technical notes:
OS: Ubuntu 18.04
Browser: Firefox 64.0 (64-bit)

**Comment by sewinter** [comment]
Super valuable feedback. The only surefire workaround we could find is changing the browser's location in the current tab rather than opening a new one. This change would only affect Firefox users. Opening a new tab is preferable, but this solution seems better than Firefox blocking a new tab from showing up or too broad permissions for the user.

**Comment by sewinter** [comment]
@birchmd marking this as closed, as it's been fixed in 0.0.35. Thanks again for your feedback!
